src/SFA.DAS.Admin.Aan.Web/Models/RemoveMember/RemoveMemberConfirmationModel.cs
namespace SFA.DAS.Admin.Aan.Web.Models.RemoveMember;

public class RemoveMemberConfirmationModel
{
    public string? NetworkDirectoryLink { get; set; }
}

src/SFA.DAS.Admin.Aan.Web/Models/RemoveMember/RemoveMemberViewModel.cs
namespace SFA.DAS.Admin.Aan.Web.Models.RemoveMember;

public class RemoveMemberViewModel : SubmitRemoveMemberModel
{
    public string? FirstName { get; set; }
    public string? RouteLink { get; set; }
    public string FullName { get; set; } = null!;
    public string? CancelLink { get; set; }
    public Guid MemberId { get; set; }
}

src/SFA.DAS.Admin.Aan.Web/Models/RemoveMember/SubmitRemoveMemberModel.cs
using SFA.DAS.Admin.Aan.Application.Constants;

namespace SFA.DAS.Admin.Aan.Web.Models.RemoveMember;

public class SubmitRemoveMemberModel
{
    public MembershipStatusType Status { get; set; }
    public bool HasRemoveConfirmed { get; set; }
}

src/SFA.DAS.Admin.Aan.Web/Controllers/ManageMembers/RemoveMemberController.cs
using FluentValidation;
using FluentValidation.AspNetCore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SFA.DAS.Aan.SharedUi.Infrastructure;
using SFA.DAS.Admin.Aan.Application.OuterApi.Members;
using SFA.DAS.Admin.Aan.Application.Services;
using SFA.DAS.Admin.Aan.Web.Authentication;
using SFA.DAS.Admin.Aan.Web.Infrastructure;
using SFA.DAS.Admin.Aan.Web.Models.RemoveMember;

namespace SFA.DAS.Admin.Aan.Web.Controllers.ManageMembers;

[Authorize(Roles = Roles.ManageMembersRole)]
public class RemoveMemberController : Controller
{
    private readonly ISessionService _sessionService;
    private readonly IOuterApiClient _outerApiClient;
    private readonly IValidator<SubmitRemoveMemberModel> _validator;
    public RemoveMemberController(ISessionService sessionService, IOuterApiClient outerApiClient, IValidator<SubmitRemoveMemberModel> validator)
    {
        _sessionService = sessionService;
        _outerApiClient = outerApiClient;
        _validator = validator;
    }

    [HttpGet]
    [Route("remove-member/{id}", Name = RouteNames.RemoveMember)]
    public async Task<IActionResult> Index([FromRoute] Guid id, CancellationToken cancellationToken)
    {
        RemoveMemberViewModel removeMemberViewModel = new RemoveMemberViewModel();
        var adminMemberId = _sessionService.GetMemberId();
        var memberProfiles = await _outerApiClient.GetMemberProfile(id, adminMemberId, cancellationToken);
        removeMemberViewModel.FullName = memberProfiles.FullName;
        removeMemberViewModel.CancelLink = Url.RouteUrl(SharedRouteNames.MemberProfile, new { id = id })!;
        removeMemberViewModel.MemberId = id;
        return View(removeMemberViewModel);
    }

    [HttpPost]
    [Route("remove-member/{id}", Name = RouteNames.RemoveMember)]
    public async Task<IActionResult> Index([FromRoute] Guid id, SubmitRemoveMemberModel submitRemoveMemberModel, CancellationToken cancellationToken)
    {
        var adminMemberId = _sessionService.GetMemberId();
        var postMemberStatusModel = new PostMemberStatusModel
        {
            Status = submitRemoveMemberModel.Status
        };
        await _outerApiClient.PostMemberLeaving(id, adminMemberId, postMemberStatusModel, cancellationToken);

        return RedirectToAction("RemoveMemberConfirmation");
    }

    [HttpGet]
    public ActionResult RemoveMemberConfirmation()
    {
        RemoveMemberConfirmationModel removeMemberConfirmationModel = new RemoveMemberConfirmationModel();
        removeMemberConfirmationModel.NetworkDirectoryLink = Url.RouteUrl(SharedRouteNames.NetworkDirectory)!;
        return View(removeMemberConfirmationModel);
    }
}

src/SFA.DAS.Admin.Aan.Web/Views/RemoveMember/Index.cshtml
@using SFA.DAS.Admin.Aan.Application.Constants;
@using SFA.DAS.Admin.Aan.Web.Models.RemoveMember;
@model RemoveMemberViewModel
@{
    ViewData["Title"] = "Remove Member";
}
<partial name="_validationSummary" />
<div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
        <h3 class="govuk-heading-m govuk-!-margin-bottom-1 govuk-hint">Manage ambassadors</h3>
        <h1 class="govuk-heading-xl govuk-!-margin-top-4 govuk-!-margin-bottom-0">Remove ambassador</h1>
        <div class="govuk-!-margin-top-4">
            <p class="govuk-!-margin-bottom-2">Use this form to remove @Model.FullName from the Apprenticeship Ambassador Network.</p>
            <p class="govuk-!-margin-bottom-2">If you are removing this person for breaching the network <a href="https://www.apprenticeships.gov.uk/influencers/aan-resources" rel="noopener" target="_blank">code of conduct</a>, please contact the central team before doing so.</p>
        </div>
        @using (Html.BeginForm("Index", "RemoveMember", new { id = Model.MemberId }, FormMethod.Post))
        {
            <div id="Status" esfa-validation-marker-for="@Model.Status" class="govuk-form-group">
                <h3 class="govuk-heading-m govuk-!-margin-bottom-4">Reason for removing from the network?</h3>
                <span asp-validation-for="@Model.Status" class="govuk-error-message"></span>
                <div class="govuk-radios" data-module="govuk-radios">
                    <div class="govuk-radios__item">
                        <input type="radio" asp-for="@Model.Status" id="inActivity" class="govuk-radios__input" value="@MembershipStatusType.Deleted">
                        <label class="govuk-label govuk-radios__label profile-govuk-radios" for="inActivity">
                            Inactivity
                        </label>
                    </div>
                    <div class="govuk-radios__item">
                        <input type="radio" asp-for="@Model.Status" id="breachCodeOfConduct" class="govuk-radios__input" value="@MembershipStatusType.Removed">
                        <label class="govuk-label govuk-radios__label profile-govuk-radios" for="breachCodeOfConduct">
                            Breach of code of conduct
                        </label>
                    </div>
                </div>
            </div>

            <div class="govuk-!-margin-top-4">
                <h3 class="govuk-heading-m govuk-!-margin-bottom-4">Are you sure you want to remove this ambassador?</h3>
                <div id="remove-ambassador-hint" class="govuk-hint">
                    Once you have removed an ambassador account, it cannot be restored. To apply to become a member again, the former ambassador must submit a new application using the portal.
                </div>
                <div class="govuk-checkboxes govuk-checkboxes">
                    <div esfa-validation-marker-for="HasRemoveConfirmed" class="govuk-form-group govuk-!-margin-bottom-1">
                        <span asp-validation-for="HasRemoveConfirmed" class="govuk-error-message"></span>
                        <div class="govuk-checkboxes__item govuk-!-margin-bottom-1" id="HasRemoveConfirmed">
                            <input type="checkbox" asp-for="HasRemoveConfirmed" class="govuk-checkboxes__input" id="hasRemoveConfirmed" name="hasRemoveConfirmed">
                            <label class="govuk-label govuk-checkboxes__label profile-govuk-checkboxes" for="hasRemoveConfirmed">
                                Yes
                            </label>
                        </div>
                    </div>
                </div>
            </div>
            <hr class="govuk-section-break govuk-section-break--l govuk-section-break--visible">
            <div class="govuk-button-group">
                <button id="saveChanges" type="submit" data-disable-on-submit="true" class="govuk-button govuk-button--warning" data-module="govuk-button">
                    Remove ambassador
                </button>
                <a class="govuk-link" href="@Model.CancelLink">Cancel</a>
            </div>
        }
    </div>
</div>

src/SFA.DAS.Admin.Aan.Web/Views/RemoveMember/RemoveMemberConfirmation.cshtml
@using SFA.DAS.Admin.Aan.Web.Models.RemoveMember;
@model RemoveMemberConfirmationModel;
@{
    ViewData["Title"] = "Remove Member Confirmation";
}
<div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
        <div class="govuk-panel govuk-panel--confirmation">
            <h1 class="govuk-panel__title">
                You have successfully removed an ambassador from the network
            </h1>
        </div>

        <h2 class="govuk-heading-m">What happens next</h2>

        <p class="govuk-body">
            The ambassador will be notified that they’ve been removed from the network and their account is no longer active. If they want to re-join the network, they must sign up again to the portal. Ambassadors who were removed for breaching the code of conduct cannot rejoin the portal.
        </p>

        <ul class="govuk-list app-icon-list">
            <li>
                <h2 class="govuk-heading-m"><a href="@Model.NetworkDirectoryLink" class="govuk-link govuk-link--no-visited-state">Manage ambassadors</a></h2>
                <p>See which ambassadors are new to the network or who hasn't been active on the network.</p>
                <svg class="app-icon-list__icon"><use href="/img/sprite.svg#icon-manage-users" /></svg>
            </li>
        </ul>
    </div>
</div>